/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import connection.ConectaBd;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import model.bean.Cliente;
import model.dao.ClienteDAO;
/**
 *
 * @author eder
 */
public class ConsultaClienteView extends javax.swing.JFrame {
    private String nome;
    /**
     * Creates new form ConsultaClienteView
     */
    public ConsultaClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtFieldNome = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Consulta Cliente");

        lbNome.setText("Nome");

        btnBuscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(147, 147, 147))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnBuscar)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {                                             

        Cliente c = new Cliente();
        ClienteDAO cDAO = new ClienteDAO();
        nome = txtFieldNome.getText();
        
        cDAO.read(c);
        cDAO.readNome(nome);

    }
    
    public ArrayList<Cliente> read() throws SQLException, ClassNotFoundException// Método para ler os dados dos clientes do banco
    {
        Connection con = ConectaBd.getConnection();
        PreparedStatement pst = null;
        ResultSet rs = null;
        ArrayList<Cliente> listClientes = new ArrayList<Cliente>();
        
        try{
            pst = con.prepareStatement("SELECT * FROM cliente WHERE cliente.nome = nome");
            //pst = con.prepareStatement("SELECT * FROM cliente WHERE cliente.nome = " + txtFieldCliente.getText());
            rs = pst.executeQuery(); // Realiza a consulta no banco
            
            while(rs.next()){
                Cliente cliente = new Cliente();
                cliente.setNome(rs.getString("nome"));
                //cliente.setNome(rs.getString(txtFieldCliente.getText()));
                listClientes.add(cliente);
            }
            
        }catch(SQLException ex){
            
        }finally{
            ConectaBd.closeConnection(con, pst, rs);
        }
        System.out.println(listClientes);
        return listClientes;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, ClassNotFoundException {
        
        Connection con = ConectaBd.getConnection();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JTextField txtFieldNome;
    // End of variables declaration//GEN-END:variables
}
