/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import connection.ConectaBd;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import model.bean.*;
import model.dao.*;
/**
 *
 * @author eder
 */
public class ConsultaClienteAgencia extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaClienteAgencia
     */
    public ConsultaClienteAgencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitlePage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbAg = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        txtFieldAg = new javax.swing.JTextField();
        txtFieldCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitlePage.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lbTitlePage.setText("Consulta Cliente Por Agência");

        jLabel1.setText("Nome do cliente");

        lbAg.setText("Estado da Agência:");

        btBuscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAg)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFieldAg)
                                    .addComponent(txtFieldCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                            .addComponent(lbTitlePage)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btBuscar)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitlePage)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAg)
                    .addComponent(txtFieldAg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btBuscar)
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public ArrayList<Cliente> read() throws SQLException, ClassNotFoundException// Método para ler os dados dos clientes do banco
    {
        Connection con = ConectaBd.getConnection();
        PreparedStatement pst = null;
        ResultSet rs = null;
        ArrayList<Cliente> listClientes = new ArrayList<Cliente>();
        
        try{
            pst = con.prepareStatement("SELECT * FROM cliente WHERE cliente.nome = nome");
            //pst = con.prepareStatement("SELECT * FROM cliente WHERE cliente.nome = " + txtFieldCliente.getText());
            rs = pst.executeQuery(); // Realiza a consulta no banco
            
            while(rs.next()){
                Cliente cliente = new Cliente();
                cliente.setNome(rs.getString("nome"));
                //cliente.setNome(rs.getString(txtFieldCliente.getText()));
                listClientes.add(cliente);
            }
            
        }catch(SQLException ex){
            
        }finally{
            ConectaBd.closeConnection(con, pst, rs);
        }
        System.out.println(listClientes);
        return listClientes;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, ClassNotFoundException {
        
        Connection con = ConectaBd.getConnection();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAg;
    private javax.swing.JLabel lbTitlePage;
    private javax.swing.JTextField txtFieldAg;
    private javax.swing.JTextField txtFieldCliente;
    // End of variables declaration//GEN-END:variables
}
